package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Passenger;
import org.mybatis.cdi.Mapper;

@SuppressWarnings("CdiManagedBeanInconsistencyInspection")
@Mapper
public interface PassengerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASSENGER
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASSENGER
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    int insert(Passenger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASSENGER
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    Passenger selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASSENGER
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    List<Passenger> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASSENGER
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    int updateByPrimaryKey(Passenger record);
}