package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Trip;
import org.mybatis.cdi.Mapper;

@SuppressWarnings("CdiManagedBeanInconsistencyInspection")
@Mapper
public interface TripMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    int insert(Trip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    Trip selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    List<Trip> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRIP
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    int updateByPrimaryKey(Trip record);
}