package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Vehicle;
import org.mybatis.cdi.Mapper;

@SuppressWarnings("CdiManagedBeanInconsistencyInspection")
@Mapper
public interface VehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VEHICLE
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VEHICLE
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    int insert(Vehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VEHICLE
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    Vehicle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VEHICLE
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    List<Vehicle> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VEHICLE
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    int updateByPrimaryKey(Vehicle record);
}