package lt.vu.mybatis.model;

public class Trip {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.ID
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.LOCATION_ID
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    private Integer locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.VEHICLE_ID
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    private Integer vehicleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.DESTINATION
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    private String destination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRIP.ORIGIN
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    private String origin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.ID
     *
     * @return the value of PUBLIC.TRIP.ID
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.ID
     *
     * @param id the value for PUBLIC.TRIP.ID
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.LOCATION_ID
     *
     * @return the value of PUBLIC.TRIP.LOCATION_ID
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.LOCATION_ID
     *
     * @param locationId the value for PUBLIC.TRIP.LOCATION_ID
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.VEHICLE_ID
     *
     * @return the value of PUBLIC.TRIP.VEHICLE_ID
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    public Integer getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.VEHICLE_ID
     *
     * @param vehicleId the value for PUBLIC.TRIP.VEHICLE_ID
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    public void setVehicleId(Integer vehicleId) {
        this.vehicleId = vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.DESTINATION
     *
     * @return the value of PUBLIC.TRIP.DESTINATION
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.DESTINATION
     *
     * @param destination the value for PUBLIC.TRIP.DESTINATION
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    public void setDestination(String destination) {
        this.destination = destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRIP.ORIGIN
     *
     * @return the value of PUBLIC.TRIP.ORIGIN
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRIP.ORIGIN
     *
     * @param origin the value for PUBLIC.TRIP.ORIGIN
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    public void setOrigin(String origin) {
        this.origin = origin;
    }
}