package lt.vu.mybatis.model;

public class Vehicle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.VEHICLE.ID
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.VEHICLE.LICENCE_PLATE
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    private String licencePlate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.VEHICLE.ID
     *
     * @return the value of PUBLIC.VEHICLE.ID
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.VEHICLE.ID
     *
     * @param id the value for PUBLIC.VEHICLE.ID
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.VEHICLE.LICENCE_PLATE
     *
     * @return the value of PUBLIC.VEHICLE.LICENCE_PLATE
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    public String getLicencePlate() {
        return licencePlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.VEHICLE.LICENCE_PLATE
     *
     * @param licencePlate the value for PUBLIC.VEHICLE.LICENCE_PLATE
     *
     * @mbg.generated Tue Apr 21 06:10:25 EEST 2020
     */
    public void setLicencePlate(String licencePlate) {
        this.licencePlate = licencePlate;
    }
}